### ISSUE TITLE
Please remove my software from your repository

### ISSUE THREAD

**Issue by devluz** [Phylliida/UnityP2P#2]
Hi Phylliida,

Your project contains my WebRTC Network Asset from here: 
https://assetstore.unity.com/packages/tools/network/webrtc-network-47846

Please remove my software from your github. It isn't suppose to be available here. It seems you are using the webrtc side plugin now anyway.

Please also make sure to remove my email address. I started to receive emails asking for help with UnityP2P.

**Comment by Phylliida** [comment]
Hey thanks for reaching out, crap I'm really sorry for doing that. Sorry
for any hassle it has caused for you, feel free to redirect those emails to
me if you'd like but you can also ignore them no worries. Either way, your
software is removed from there now :)
